const DOMAIN_DEPENDENCIES = {};

const APPLICATION_DEPENDENCIES = {};

const INFRASTRUCTURE_DEPENDENCIES = {};

const PRESENTATION_DEPENDENCIES = {};

export const DEPENDENCIES = {
  ...DOMAIN_DEPENDENCIES,
  ...APPLICATION_DEPENDENCIES,
  ...INFRASTRUCTURE_DEPENDENCIES,
  ...PRESENTATION_DEPENDENCIES,
};

export type Dependency = (typeof DEPENDENCIES)[keyof typeof DEPENDENCIES];
